### ISSUE TITLE
[DotNetOpenAuth] Requesting help to address Protocol error

### ISSUE THREAD

**Issue by iamSathishMohan** [DotNetOpenAuth/DotNetOpenAuth.Samples#29]
@AArnott @DavidChristiansen 

I have problem with **DotNetOpenAuth v4.3.4.13329**. During the relying party discovery, it throws following error.

```
DEBUG [2019-06-28 14:32:20,789] - HTTP GET http://localhost/sub/
DEBUG [2019-06-28 14:32:20,792] - HTTP GET http://localhost/sub/en
ERROR [2019-06-28 14:32:20,815] - Protocol error: An HTTP request to the realm URL (http://localhost/sub/) resulted in a redirect, which is not allowed during relying party discovery.
   at DotNetOpenAuth.Messaging.ErrorUtilities.VerifyProtocol(Boolean condition, String unformattedMessage, Object[] args)
   at DotNetOpenAuth.OpenId.Realm.Discover(IDirectWebRequestHandler requestHandler, Boolean allowRedirects)
   at DotNetOpenAuth.OpenId.Realm.DiscoverReturnToEndpoints(IDirectWebRequestHandler requestHandler, Boolean allowRedirects)
   at DotNetOpenAuth.OpenId.Provider.HostProcessedRequest.IsReturnUrlDiscoverableCore(IDirectWebRequestHandler requestHandler)
   at DotNetOpenAuth.OpenId.Provider.HostProcessedRequest.IsReturnUrlDiscoverable(IDirectWebRequestHandler requestHandler)
```

I pretty much understood the problem here. Its trying to find the URL **http://localhost/sub/**, but it gets redirected to **http://localhost/sub/en** because of i18n localization. Could you please help me to get rid of this error message ?

**Comment by AArnott** [comment]
This library is not actively supported any more.

You should fix this by disabling the localization redirect. Per the openid protocol, realm discovery is not allowed to result in a redirect.
As to how to keep your localization scenario working without a forced redirect at least during realm discovery, I don't know as I haven't implemented localization via redirects before.
